### ISSUE TITLE
Gradle Tasks do not have description.

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#10]
It will be good if `gradle tasks` showed tasks with description, Also would be beneficial if all tasks created by multiproject-git-gradle are grouped together based on functionality, 

like : Release Tasks , Clone and Setup Tasks etc.

Running gradle tasks displays the following information now:

```
Other tasks
-----------
buildApps
buildExamples
clean
gitBranchList
gitCommit
gitPush
gitStatus
release
uploadArchives
```

**Comment by akhikhl** [comment]
All tasks are now supplied with group and description.

**Comment by kavink** [comment]
:+1:
