### ISSUE TITLE
Example project publishing when using ARF

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#11]
Is it possible to have an example of project using ARF to release/publish artifacts either to a central maven or artifactory server or maybe just local maven repo.

**Comment by akhikhl** [comment]
Please see https://github.com/akhikhl/multiproject-git-gradle#publishing-to-maven-repositories. The concrete steps are:
1. add `apply plugin: 'maven'`.
2. configure uploadArchives task, as shown in documentation.
3. add releaseDeployTasks property to "config.gradle".

**Comment by kavink** [comment]
I tried install, Builds kept failing because it cannot find released versions. any thoughts ?

**Comment by kavink** [comment]
This is also fixed.
