### ISSUE TITLE
Does an ARF release uploads Archives or that has to be configured ?

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#12]
The [gradle-release plugin](https://github.com/townsfolk/gradle-release) , Does it call upload archives automatically when a release version is built and when snapshot is build. Does it deploy both in same release action ?

Also how can we change it to also maybe call [artifactory publish task, if plugin is used](http://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin)  or maven deployer is used?

**Comment by kavink** [comment]
@akhikhl Any thoughts on this ?

**Comment by akhikhl** [comment]
multiproject-git-gradle version 1.0.25 allows to publish release and snapshot artifacts to local or remote maven repo. See documentation at: https://github.com/akhikhl/multiproject-git-gradle#publishing-to-maven-repositories

**Comment by kavink** [comment]
Looks like there is some ordering sequence bug or something. i.e. task `releaseBuild` is being called for all tasks, but artifacts are not being deployed for downstream jobs to do resolution against. 

Please can you investigate to find the root cause for the bug ?

**Comment by kavink** [comment]
This is fixed in latest release
