### ISSUE TITLE
Ability for Project name to have a "-" dash, So it can be used in dependencies

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#16]
If a project name has a "-" in it, It cannot be used as a variable in dependencies, as the gradle will not build as fails as it does not like it.

e.g. if git repository and rootProject.name is `project-1`, then gradle.properties will be `project-1_version`

and dependencies would be 
`compile "group1:libB:$project-1_version"`

The build will fail.

Possible solution would be to automatically replace - with _ or have ability to user specify variable name other than default.

**Comment by akhikhl** [comment]
The problem is well reproducible. I like your idea of replacing '-' with '_'  - it will allow to fix the problem.

**Comment by kavink** [comment]
Thanks, Ill keep an watch for a fix , so i can test again.

**Comment by akhikhl** [comment]
Fixed in version 1.0.17.
Example setup: https://dl.dropboxusercontent.com/u/15089387/multi-project-setup-dashed-project-name.zip

**Comment by kavink** [comment]
Awesome!!! :+1: Thanks... let me test it...

**Comment by kavink** [comment]
Works! Closing it, Fixed in : ef8e3316af793beeb84d0d4897afa9167aad1276
