### ISSUE TITLE
Summary whenever ARF is used

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#5]
Whenever ARF features are used, a summary should be generated in the end on what versions were released and what is the current snapshot versions.

Also if there are any failures like a git failure or release failure, some detailed logging would be helpful

**Comment by akhikhl** [comment]
done in version 1.0.16

**Comment by kavink** [comment]
Looks good:

```
Release is finished. The following projects were released:
Project Name    | Release Version   | New Version
project1    | 2.1           | 2.2-SNAPSHOT
project2    | 1.1           | 1.2-SNAPSHOT
project3    | 3.1           | 3.2

```
